#!/bin/sh

exit_0()
{
  exit 0
}

fancy_exit()
{
  echo "Exiting..."
  exit 0
}

get_help()
{
  help="Usage: dds\nOptions:\n--help, -help, or -h displays this information.\n--version, -version, or -v displays dds version information.\n\ndds does not support any options other than those shown here."
}

get_version()
{
  version="dds version 1.0"
}

check_if_su()
{
  if [ "$(id -u)" != 0 ]; then
    echo "Please run with su privileges"
    fancy_exit
  fi
}

validate_file()
{
  FILE=$1
  if [ ! -e "$FILE" ]; then
    echo "Not a valid file"
    fancy_exit
  fi
}

check_illumos()
{
  case "$(uname -o)" in
    illumos)
      # illumos distributions like OpenIndiana support this feature 
      status_supported="true";;
    *)
      # Oracle Solaris 11.4 does not support this feature
      status_supported="false"
  esac
}

check_os()
{
  os_type="$(uname -s)"
  echo "OS: $os_type"
  case "$os_type" in
    # Platforms known to support the status progress indicator
    Linux | FreeBSD | DragonFly)
      status_supported="true";;
    SunOS)
      check_illumos;;
    *)
      status_supported="false"
  esac
}

list_disks()
{
  case "$os_type" in
    Darwin)
      if [ "$(command -v diskutil)" ]; then
        diskutil list
      else
        echo "Your OS was detected to be ${os_type}, but the diskutil command could not be found."
      fi;;
    Linux)
      lsblk;;
    *)
      echo "Functionality not implemented for your OS: ${os_type}"
  esac
}

unmount_disks()
{
  case "$os_type" in
    Darwin)
      if [ "$(command -v diskutil)" ]; then
        diskutil unmountDisk $1
      else
        echo "Your OS was detected to be ${os_type}, but the diskutil command could not be found."
      fi;;
    Linux)
      unmount $1;;
    *)
      echo "Functionality not implemented for your OS: ${os_type}"
  esac
}

run_dd()
{
  echo "Beginning process..."
  case $status_supported in
    "true")
      dd if="$src" of="$dest" bs="$bs" conv=noerror,sync status=progress;;
    "false")
      dd if="$src" of="$dest" bs="$bs" conv=noerror,sync;;
    *)
      echo "Well... this is no good. Feel free to open an issue here: https://github.com/Adobe-Android/dd-safe/issues/new"
  esac
}

main()
{
  echo "Welcome to dd-safe"
  echo "------------------"
  check_if_su
  check_os
  echo "------------------"
  list_disks
  echo "------------------"
  printf 'Enter data source: '
  read -r src
  validate_file "$src"
  printf 'Enter data destination: '
  read -r dest
  validate_file "$dest"
  unmount_disks "$dest"
  printf 'What block size do you want to use? (default: 64k, 128k, 1m): '
  read -r bs_in

  case $bs_in in
    "" | " ")
      bs="64k"
      echo "No value provided. Setting default value: $bs";;
    *)
      bs=$bs_in;;
  esac

  echo "Preparing to copy from source: $src to destination: $dest with block size: $bs"
  printf 'Do you want to continue? (y/n) '
  read -r confirm

  case $confirm in
    "y" | "Y")
      run_dd $status_supported;;
    *)
    fancy_exit;;
  esac
}

case $1 in
  '')
    main;;
  "--version" | "-version" | "-v")
    get_version
    echo "$version"
    exit_0;;
  "--help" | "-help" | "-h")
    get_help
    echo "$help"
    exit_0;;
  *)
    printf "dds: invalid option\nuse 'dds --help' to show valid options.\n"
    exit_0
esac
