.\" Manpage for dds.
.TH DDS 1 "Jul 30, 2020" "1.0" "dds"
.SH NAME
dds \- A safer and simpler way to use dd
.SH SYNOPSIS
dds
.SH DESCRIPTION
dds is a high-level posix shell wrapper around dd. It focuses on serving the most common use cases with simplicity, safety, and portability in mind.
.SH OPTIONS
dds does not take any options. However, --help and --version work as expected.
.SH LICENSE
MIT License - \fI\s-1https://choosealicense.com/licenses/mit/\fR
.SH SEE ALSO
dd(1)
.SH BUGS
Please submit all issues here: \fI\s-1https://github.com/Adobe-Android/dd-safe/issues/new\fR
.SH AUTHOR
David Brown - \fI\s-1https://github.com/Adobe-Android\fR
.SH HOME
\fI\s-1https://github.com/Adobe-Android/dd-safe\fR
